// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetNdbDbServersDbserverVmInfoInfoResult
    {
        public readonly ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigResult> BpgConfigs;
        public readonly ImmutableDictionary<string, string> SecureInfo;

        [OutputConstructor]
        private GetNdbDbServersDbserverVmInfoInfoResult(
            ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigResult> bpgConfigs,

            ImmutableDictionary<string, string> secureInfo)
        {
            BpgConfigs = bpgConfigs;
            SecureInfo = secureInfo;
        }
    }
}
