// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetNdbDbServersDbserverVmInfoInfoBpgConfigResult
    {
        public readonly ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigBpgDbParamResult> BpgDbParams;
        public readonly ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageResult> Storages;
        public readonly ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigVmPropertyResult> VmProperties;

        [OutputConstructor]
        private GetNdbDbServersDbserverVmInfoInfoBpgConfigResult(
            ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigBpgDbParamResult> bpgDbParams,

            ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageResult> storages,

            ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigVmPropertyResult> vmProperties)
        {
            BpgDbParams = bpgDbParams;
            Storages = storages;
            VmProperties = vmProperties;
        }
    }
}
