// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageResult
    {
        public readonly ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageArchiveStorageResult> ArchiveStorages;
        public readonly ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageDataDiskResult> DataDisks;
        public readonly ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageLogDiskResult> LogDisks;

        [OutputConstructor]
        private GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageResult(
            ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageArchiveStorageResult> archiveStorages,

            ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageDataDiskResult> dataDisks,

            ImmutableArray<Outputs.GetNdbDbServersDbserverVmInfoInfoBpgConfigStorageLogDiskResult> logDisks)
        {
            ArchiveStorages = archiveStorages;
            DataDisks = dataDisks;
            LogDisks = logDisks;
        }
    }
}
