// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class NdbDbserverVMMaintenanceTasks
    {
        public readonly string? MaintenanceWindowId;
        public readonly ImmutableArray<Outputs.NdbDbserverVMMaintenanceTasksTask> Tasks;

        [OutputConstructor]
        private NdbDbserverVMMaintenanceTasks(
            string? maintenanceWindowId,

            ImmutableArray<Outputs.NdbDbserverVMMaintenanceTasksTask> tasks)
        {
            MaintenanceWindowId = maintenanceWindowId;
            Tasks = tasks;
        }
    }
}
