// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommand
    {
        /// <summary>
        /// command that you want to run after patching the OS/DB
        /// </summary>
        public readonly string? PostCommand;
        /// <summary>
        /// command that you want to run before patching the OS/DB
        /// </summary>
        public readonly string? PreCommand;

        [OutputConstructor]
        private NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommand(
            string? postCommand,

            string? preCommand)
        {
            PostCommand = postCommand;
            PreCommand = preCommand;
        }
    }
}
