// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class NdbMaintenanceTaskEntityTaskAssociationPayload
    {
        /// <summary>
        /// Pre Post command of Task 
        /// * `pre_post_command.pre_command`: pre command of task
        /// * `pre_post_command.post_command`: post command of task
        /// </summary>
        public readonly ImmutableArray<Outputs.NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommand> PrePostCommands;

        [OutputConstructor]
        private NdbMaintenanceTaskEntityTaskAssociationPayload(ImmutableArray<Outputs.NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommand> prePostCommands)
        {
            PrePostCommands = prePostCommands;
        }
    }
}
