// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class NdbRegisterDatabaseProperty
    {
        /// <summary>
        /// - (Required) name of time machine
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// - (Required) value for argument
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private NdbRegisterDatabaseProperty(
            string? name,

            string? value)
        {
            Name = name;
            Value = value;
        }
    }
}
