// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Outputs
{

    [OutputType]
    public sealed class ServiceGroupServiceListUdpPortRangeList
    {
        /// <summary>
        /// End Port (Int)
        /// 
        /// 
        /// See detailed information in [Nutanix Service Groups](https://www.nutanix.dev/api_references/prism-central-v3/#/38492a5cb53e2-create-a-new-service-group).
        /// </summary>
        public readonly int? EndPort;
        /// <summary>
        /// - (Optional) Start Port (Int)
        /// </summary>
        public readonly int? StartPort;

        [OutputConstructor]
        private ServiceGroupServiceListUdpPortRangeList(
            int? endPort,

            int? startPort)
        {
            EndPort = endPort;
            StartPort = startPort;
        }
    }
}
