# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = [
    'GetNdbDbServersResult',
    'AwaitableGetNdbDbServersResult',
    'get_ndb_db_servers',
]

@pulumi.output_type
class GetNdbDbServersResult:
    """
    A collection of values returned by getNdbDbServers.
    """
    def __init__(__self__, dbservers=None, id=None):
        if dbservers and not isinstance(dbservers, list):
            raise TypeError("Expected argument 'dbservers' to be a list")
        pulumi.set(__self__, "dbservers", dbservers)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def dbservers(self) -> Sequence['outputs.GetNdbDbServersDbserverResult']:
        return pulumi.get(self, "dbservers")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetNdbDbServersResult(GetNdbDbServersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNdbDbServersResult(
            dbservers=self.dbservers,
            id=self.id)


def get_ndb_db_servers(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNdbDbServersResult:
    """
    List of all Database Server VM in Nutanix Database Service

    ## Example Usage

    ```python
    import pulumi
    import pulumi_nutanix as nutanix

    dbservers = nutanix.get_ndb_db_servers()
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nutanix:index/getNdbDbServers:getNdbDbServers', __args__, opts=opts, typ=GetNdbDbServersResult).value

    return AwaitableGetNdbDbServersResult(
        dbservers=pulumi.get(__ret__, 'dbservers'),
        id=pulumi.get(__ret__, 'id'))
