// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nutanix

import (
	"github.com/jacobbmay/pulumi-nutanix/sdk/go/nutanix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Describes a List of Karbon private registry entry
func GetKarbonPrivateRegistries(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetKarbonPrivateRegistriesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetKarbonPrivateRegistriesResult
	err := ctx.Invoke("nutanix:index/getKarbonPrivateRegistries:getKarbonPrivateRegistries", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getKarbonPrivateRegistries.
type GetKarbonPrivateRegistriesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                string                                      `pulumi:"id"`
	PrivateRegistries []GetKarbonPrivateRegistriesPrivateRegistry `pulumi:"privateRegistries"`
}
