// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nutanix

import (
	"github.com/jacobbmay/pulumi-nutanix/sdk/go/nutanix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Describes Recovery Plans
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/jacobbmay/pulumi-nutanix/sdk/go/nutanix"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := nutanix.GetRecoveryPlans(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetRecoveryPlans(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetRecoveryPlansResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetRecoveryPlansResult
	err := ctx.Invoke("nutanix:index/getRecoveryPlans:getRecoveryPlans", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getRecoveryPlans.
type GetRecoveryPlansResult struct {
	// version of the API
	ApiVersion string `pulumi:"apiVersion"`
	// List of Recovery Plans
	Entities []GetRecoveryPlansEntity `pulumi:"entities"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
