// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Inputs
{

    public sealed class NdbDbserverVMPostgresDatabaseArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientPublicKey")]
        public Input<string>? ClientPublicKey { get; set; }

        [Input("vmName", required: true)]
        public Input<string> VmName { get; set; } = null!;

        public NdbDbserverVMPostgresDatabaseArgs()
        {
        }
        public static new NdbDbserverVMPostgresDatabaseArgs Empty => new NdbDbserverVMPostgresDatabaseArgs();
    }
}
