// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Inputs
{

    public sealed class NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommandGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// command that you want to run after patching the OS/DB
        /// </summary>
        [Input("postCommand")]
        public Input<string>? PostCommand { get; set; }

        /// <summary>
        /// command that you want to run before patching the OS/DB
        /// </summary>
        [Input("preCommand")]
        public Input<string>? PreCommand { get; set; }

        public NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommandGetArgs()
        {
        }
        public static new NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommandGetArgs Empty => new NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommandGetArgs();
    }
}
