// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Inputs
{

    public sealed class NdbMaintenanceTaskEntityTaskAssociationPayloadGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("prePostCommands")]
        private InputList<Inputs.NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommandGetArgs>? _prePostCommands;

        /// <summary>
        /// Pre Post command of Task 
        /// * `pre_post_command.pre_command`: pre command of task
        /// * `pre_post_command.post_command`: post command of task
        /// </summary>
        public InputList<Inputs.NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommandGetArgs> PrePostCommands
        {
            get => _prePostCommands ?? (_prePostCommands = new InputList<Inputs.NdbMaintenanceTaskEntityTaskAssociationPayloadPrePostCommandGetArgs>());
            set => _prePostCommands = value;
        }

        public NdbMaintenanceTaskEntityTaskAssociationPayloadGetArgs()
        {
        }
        public static new NdbMaintenanceTaskEntityTaskAssociationPayloadGetArgs Empty => new NdbMaintenanceTaskEntityTaskAssociationPayloadGetArgs();
    }
}
