// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Inputs
{

    public sealed class NdbRegisterDatabasePropertyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - (Required) name of time machine
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// - (Required) value for argument
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public NdbRegisterDatabasePropertyArgs()
        {
        }
        public static new NdbRegisterDatabasePropertyArgs Empty => new NdbRegisterDatabasePropertyArgs();
    }
}
