// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Inputs
{

    public sealed class ServiceGroupServiceListUdpPortRangeListArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// End Port (Int)
        /// 
        /// 
        /// See detailed information in [Nutanix Service Groups](https://www.nutanix.dev/api_references/prism-central-v3/#/38492a5cb53e2-create-a-new-service-group).
        /// </summary>
        [Input("endPort")]
        public Input<int>? EndPort { get; set; }

        /// <summary>
        /// - (Optional) Start Port (Int)
        /// </summary>
        [Input("startPort")]
        public Input<int>? StartPort { get; set; }

        public ServiceGroupServiceListUdpPortRangeListArgs()
        {
        }
        public static new ServiceGroupServiceListUdpPortRangeListArgs Empty => new ServiceGroupServiceListUdpPortRangeListArgs();
    }
}
