// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JacobBMay.Nutanix.Inputs
{

    public sealed class UserGroupsCategoryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// - (Required) The name of the SAML group which the IDP provides.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public UserGroupsCategoryArgs()
        {
        }
        public static new UserGroupsCategoryArgs Empty => new UserGroupsCategoryArgs();
    }
}
