// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * List of all Database Server VM in Nutanix Database Service
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nutanix from "@pulumi/nutanix";
 *
 * const dbservers = nutanix.getNdbDbServers({});
 * ```
 */
export function getNdbDbServers(opts?: pulumi.InvokeOptions): Promise<GetNdbDbServersResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("nutanix:index/getNdbDbServers:getNdbDbServers", {
    }, opts);
}

/**
 * A collection of values returned by getNdbDbServers.
 */
export interface GetNdbDbServersResult {
    readonly dbservers: outputs.GetNdbDbServersDbserver[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
/**
 * List of all Database Server VM in Nutanix Database Service
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as nutanix from "@pulumi/nutanix";
 *
 * const dbservers = nutanix.getNdbDbServers({});
 * ```
 */
export function getNdbDbServersOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetNdbDbServersResult> {
    return pulumi.output(getNdbDbServers(opts))
}
